package POJO;
// Generated 02-feb-2022 12:00:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


     private String mat;
     private String apelNom;
     private String poblacion;
     private String telefono;
     private Set<Notas> notases = new HashSet<Notas>(0);

    public Alumnos() {
    }

    public Alumnos(String mat, String apelNom, String poblacion, String telefono) {
        this.mat = mat;
        this.apelNom = apelNom;
        this.poblacion = poblacion;
        this.telefono = telefono;
    }

	
    public Alumnos(String mat) {
        this.mat = mat;
    }
    public Alumnos(String mat, String apelNom, String poblacion, String telefono, Set<Notas> notases) {
       this.mat = mat;
       this.apelNom = apelNom;
       this.poblacion = poblacion;
       this.telefono = telefono;
       this.notases = notases;
    }
   
    public String getMat() {
        return this.mat;
    }
    
    public void setMat(String mat) {
        this.mat = mat;
    }
    public String getApelNom() {
        return this.apelNom;
    }
    
    public void setApelNom(String apelNom) {
        this.apelNom = apelNom;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public String getTelefono() {
        return this.telefono;
    }

    @Override
    public String toString() 
    {
        return "Alumnos{" + "mat=" + mat + ", apelNom=" + apelNom + ", poblacion=" + poblacion + ", telefono=" + telefono + ", notases=" + notases + '}';
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set<Notas> getNotases() {
        return this.notases;
    }
    
    public void setNotases(Set<Notas> notases) {
        this.notases = notases;
    }




}


