package POJO;
// Generated 02-feb-2022 12:00:14 by Hibernate Tools 4.3.1



/**
 * NotasId generated by hbm2java
 */
public class NotasId  implements java.io.Serializable {


     private String mat;
     private byte cod;

    public NotasId() {
    }

    public NotasId(String mat, byte cod) {
       this.mat = mat;
       this.cod = cod;
    }
   
    public String getMat() {
        return this.mat;
    }
    
    public void setMat(String mat) {
        this.mat = mat;
    }
    public byte getCod() {
        return this.cod;
    }
    
    public void setCod(byte cod) {
        this.cod = cod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NotasId) ) return false;
		 NotasId castOther = ( NotasId ) other; 
         
		 return ( (this.getMat()==castOther.getMat()) || ( this.getMat()!=null && castOther.getMat()!=null && this.getMat().equals(castOther.getMat()) ) )
 && (this.getCod()==castOther.getCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMat() == null ? 0 : this.getMat().hashCode() );
         result = 37 * result + this.getCod();
         return result;
   }   

  


}


