package POJOS;
// Generated 23-feb-2022 17:42:23 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private int codprod;
     private String nombre;
     private BigDecimal precio;
     private Set<Ventas> ventases = new HashSet<Ventas>(0);

    public Productos() {
    }

	
    public Productos(int codprod) {
        this.codprod = codprod;
    }
    public Productos(int codprod, String nombre, BigDecimal precio, Set<Ventas> ventases) {
       this.codprod = codprod;
       this.nombre = nombre;
       this.precio = precio;
       this.ventases = ventases;
    }
   
    public int getCodprod() {
        return this.codprod;
    }
    
    public void setCodprod(int codprod) {
        this.codprod = codprod;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Set<Ventas> getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set<Ventas> ventases) {
        this.ventases = ventases;
    }

    @Override
    public String toString() {
    return this.nombre;
       }




}


