package POJOS;
// Generated 23-feb-2022 17:42:23 by Hibernate Tools 4.3.1


import com.sun.imageio.plugins.jpeg.JPEG;
import java.math.BigDecimal;

/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private int id;
     private Productos productos;
     private String codVend;
     private Integer unidades;
     private BigDecimal ganancia;

    public Ventas(String codVend) {
        this.codVend = codVend;
    }

    public Ventas() {
    }

    
	
    public Ventas(int id) {
        this.id = id;
    }
    public Ventas(int id, Productos productos, String codVend, Integer unidades, BigDecimal ganancia) {
       this.id = id;
       this.productos = productos;
       this.codVend = codVend;
       this.unidades = unidades;
       this.ganancia = ganancia;
    }

    public Ventas(String cod_vendedor, Productos codProd) {
       this.codVend = cod_vendedor;
       this.productos = codProd;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public String getCodVend() {
        return this.codVend;
    }
    
    public void setCodVend(String codVend) {
        this.codVend = codVend;
    }
    public Integer getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(Integer unidades) {
        this.unidades = unidades;
    }
    public BigDecimal getGanancia() {
        return this.ganancia;
    }
    
    public void setGanancia(BigDecimal ganancia) {
        this.ganancia = ganancia;
    }

    @Override
    public String toString() {
        return "Ventas{" + "id=" + id + ", productos=" + productos.toString() + ", codVend=" + codVend + ", unidades=" + unidades + ", ganancia=" + ganancia + '}';
    }


}


